# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  SHOC_PUBLIC_REGISTRY: ghcr.io
  SHOC_PUBLIC_REPOSITORY: ${{ github.repository }}/public
  SHOC_PUBLIC_VERSION: ${{ github.sha }}
  SHOC_PUBLIC_SERVICES: shoc-builder shoc-identity shoc-webgtw shoc-executor shoc-database-migrator shoc-dind shoc-database-sql shoc-ui

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
        cache-dependency-path: '**/yarn.lock'
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Builder
      run: dotnet publish Shoc.Builder/Shoc.Builder.csproj -c Release -o Shoc.Builder/bin/Release/net6.0/publish/
    
    - name: Publish Identity
      run: dotnet publish Shoc.Identity/Shoc.Identity.csproj -c Release -o Shoc.Identity/bin/Release/net6.0/publish/

    - name: Publish Executor
      run: dotnet publish Shoc.Executor/Shoc.Executor.csproj -c Release -o Shoc.Executor/bin/Release/net6.0/publish/

    - name: Publish Web Gateway
      run: dotnet publish Shoc.Webgtw/Shoc.Webgtw.csproj -c Release -o Shoc.Webgtw/bin/Release/net6.0/publish/

    - name: Publish Database Migrator
      run: dotnet publish Shoc.Database.Migrator/Shoc.Database.Migrator.csproj -c Release -o Shoc.Database.Migrator/bin/Release/net6.0/publish/

    - name: Publish Shoc Ui
      run: |
      yarn --cwd Shoc.Ui/
      yarn --cwd Shoc.Ui/ build
  
    - name: Build all images
      run: docker-compose build $SHOC_PUBLIC_SERVICES
   
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.SHOC_PUBLIC_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.SHOC_GHCR_TOKEN }}

    - name: Push all images
      run: docker-compose push $SHOC_PUBLIC_SERVICES
